# Generated by Django 3.2.9 on 2021-12-07 08:32

from django.db import migrations, models
import feed.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('dob', models.DateField(validators=[feed.models.MinAgeValidator(18)], verbose_name='Дата рождения')),
                ('text', models.TextField(verbose_name='Текст объявления')),
                ('gender', models.CharField(choices=[('M', 'Парень'), ('F', 'Девушка')], default='M', max_length=1, verbose_name='Кто вы?')),
                ('interlocutor', models.CharField(choices=[('M', 'Парень'), ('F', 'Девушка'), ('P', 'Пара')], default='F', max_length=1, verbose_name='Кого ищете?')),
                ('purpose_of_acquaintance', models.CharField(choices=[('UNT', 'Не важно'), ('ROM', 'Серьезные отношения'), ('TRV', 'Совместное путешествие'), ('VTL', 'Виртуальное общение'), ('SEX', 'Секс')], default='UNT', max_length=3, verbose_name='Цель знакомств')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания объявления')),
                ('is_prime', models.BooleanField(default=False, verbose_name='Премиум объявление')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Статус проверки')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Статус подтверждения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('uuid_ad', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'db_table': 'announcement',
            },
        ),
    ]
